# additional files:
# costume weapon positioning settings: sectionroot/userdata/system/equipment/weaponequippedpositionuserdata.user

# TODO hardcoded-catalog patcher: sectionroot/userdata/esweaponuserdata.user

entities:
  weapon:
    enums:
    - name: offline.EquipmentDefine.WeaponType
      format: "{name}"
      primary: true
    to_string: "Weapon {name} {displayName}"
    fields:
      # - name: data
      #   type: object
      #   label: Data
      #   params:
      #     field: "{name:lower()}"
      #     classname: offline.gamemastering.item.WeaponElement
      - name: catalog
        label: Catalog data
        required: true
        resource:
          id: [_Type]
          type: array-file
          classname: offline.WeaponPrefabUserData.WeaponParam
          file: sectionroot/userdata/system/equipment/weaponprefabuserdata.user
          params:
            nested: false
      - name: motionResources
        required: true
        resource:
          id: [_WeaponType]
          type: array-file
          classname: offline.survivor.motion.WeaponCharacterMotionResourcePrefabSettings
          file: sectionroot/userdata/system/equipment/weaponcharactermotionresourceuserdata.user
          params:
            nested: false
      - name: name
        label: Weapon code name
        required: true
        resource:
          type: string
          params:
            regex: "^WP[0-9_]{4}$"
            regexDescription: "Example: WP0123"
            tooltip: Enter a code name for the weapon. This should be unique across all weapons and is used for enum entries.
            initial: "{id:enum(offline.EquipmentDefine.WeaponType)}"
        display_after: start
      - name: displayName
        field_type: keyed_message
        required: true
        resource:
          type: msg
          file: escape/message/mes_weapon.msg
          params:
            key_format: "Weapon_{name:lower()}"
        display_after: name
      - name: prefab
        label: Weapon prefab
        required: true
        field_type: resource_link
        resource:
          resource_type: prefab
          params:
            path: "{catalog?.Prefab?.Path}"

  # offline.gamemastering.item.WeaponElement:
  #   type: hardcoded-catalog
  #   classname: offline.gamemastering.item.WeaponElementList
  #   file: sectionroot/userdata/ropewayweaponuserdata.user

classes:
  offline.WeaponPrefabUserData.WeaponParam:
    to_string: "Weapon {_Type:enum(offline.EquipmentDefine.WeaponType)} ({_Name}) {Prefab.Path}"
  offline.survivor.motion.WeaponCharacterMotionResourceContainer:
    to_string: "Motion Prefab {Prefab.Path}"
  offline.WeaponEquippedPositionUserData.PlayerParam:
    to_string: "{PlayerType:enum(offline.PlayerDefine.PlayerType)}"
  offline.WeaponEquippedPositionUserData.CostumeParam:
    to_string: "{CostumeType:enum(offline.SurvivorDefine.Costume)}"
  offline.WeaponEquippedPositionUserData.EquipParam:
    to_string: "{WeaponType:enum(offline.EquipmentDefine.WeaponType)}"
