# additional files:
# costume weapon positioning settings: SectionRoot/UserData/system/equipment/weaponequippedpositionuserdata.user

# TODO hardcoded-catalog patcher: SectionRoot/UserData/esweaponuserdata.user

entities:
  weapon:
    enums:
    - name: offline.EquipmentDefine.WeaponType
      format: "{name}"
      primary: true
    to_string: "Weapon {name} {displayName}"
    before_create:
    - type: string-input
      field: name
    fields:
      # - name: data
      #   type: object
      #   label: Data
      #   params:
      #     field: "{name:lower()}"
      #     classname: offline.gamemastering.item.WeaponElement
      - name: catalog
        label: Catalog data
        required: true
        resource:
          id: [_Type]
          type: object-catalog
          custom_id_range: [1000, 9999999]
          classname: offline.WeaponPrefabUserData.WeaponParam
          file: SectionRoot/UserData/system/equipment/weaponprefabuserdata.user
          params:
            nested: false
            duplicate_assets_on_create: true
      - name: motionResources
        required: true
        resource:
          id: [_WeaponType]
          type: object-catalog
          classname: offline.survivor.motion.WeaponCharacterMotionResourcePrefabSettings
          file: SectionRoot/UserData/system/equipment/weaponcharactermotionresourceuserdata.user
          params:
            nested: false
      - name: name
        label: Weapon code name
        required: true
        resource:
          type: string
          params:
            regex: "^WP[0-9_]{4}$"
            regex_description: "Example: WP0123"
            tooltip: Enter a code name for the weapon. This should be unique across all weapons and is used for enum entries.
            initial: "{id:enum(offline.EquipmentDefine.WeaponType)}"
            unique_enum: offline.EquipmentDefine.WeaponType
        display_after: start
      - name: displayName
        field_type: keyed_message
        required: true
        resource:
          type: msg
          file: escape/message/mes_weapon.msg
          params:
            key_format: "Weapon_{name:lower()}"
        display_after: name

  # offline.gamemastering.item.WeaponElement:
  #   type: hardcoded-catalog
  #   classname: offline.gamemastering.item.WeaponElementList
  #   file: SectionRoot/UserData/ropewayweaponuserdata.user

classes:
  offline.WeaponPrefabUserData.WeaponParam:
    to_string: "Weapon {_Type:enum(offline.EquipmentDefine.WeaponType)} ({_Name}) {Prefab.Path}"
  offline.survivor.motion.WeaponCharacterMotionResourceContainer:
    to_string: "Motion Prefab {Prefab.Path}"
  offline.WeaponEquippedPositionUserData.PlayerParam:
    to_string: "{PlayerType:enum(offline.PlayerDefine.PlayerType)}"
  offline.WeaponEquippedPositionUserData.CostumeParam:
    to_string: "{CostumeType:enum(offline.SurvivorDefine.Costume)}"
  offline.WeaponEquippedPositionUserData.EquipParam:
    to_string: "{WeaponType:enum(offline.EquipmentDefine.WeaponType)}"
