entities:
  costumes.closet:
    to_string: "Costume {closet._CharacterID.Hash:enum(ce.CharacterDefine)} #{id}"
    fields:
      - name: closet
        resource:
          id: [{ path: _CharacterID.Hash, class: app.ObjectDefine }]
          type: item-list-catalog
          classname: app.Costume.Closet
          field: _Closets
          params:
            nested: false
          files:
          - SingletonUserData/Catalog/CostumeCatalogUserData_1st_maincontents.user
          - SingletonUserData/Catalog/CostumeCatalogUserData_2nd_maincontents.user
          - SingletonUserData/Catalog/DLC/CostumeCatalogUserData_DLC0001.user
          - SingletonUserData/Catalog/DLC/CostumeCatalogUserData_DLC0002.user

classes:
  app.Costume.Closet:
    to_string: "Closet {_CharacterID.Hash:enum(ce.CharacterDefine)} (#{_CharacterID.Hash})"
  app.Costume.Outfit:
    to_string: "Outfit {_CostumeIDHash._TypeSelectHash:enum(ce.CostumeID)} [{_CostumeIDHash._TypeSelectHash}]"
  app.Costume.Part:
    to_string: "{_Name} | Path={_Prefab.Path}"
  app.CostumeIDSelector:
    to_string: "Costume ID {_TypeSelectHash:enum(ce.CostumeID)} [{_TypeSelectHash}]"
  app.gui.CostumeMenuTriggerRelationData.Unit:
    to_string: "Costume Menu Relation Unit [Costume={_CostumeID:enum(ce.CostumeID)}]"
  app.CostumeSwitchingUserData.CostumeSwitchingUnit:
    to_string: "Costume Switching Unit {_SrcCostumeIDHash._TypeSelectHash:enum(ce.CostumeID)} => {_DestCostumeIDHash._TypeSelectHash:enum(ce.CostumeID)}"
