
classes:
  app.ObjectDefine:
    to_string: "ObjectDefine {Hash} ({Hash:enum(ce.ObjectDefine)})"
  app.ChapterIDSelector:
    to_string: "Chapter ID Selector {_TypeSelectHash}"
  app.ItemCatalogUserData.Data:
    to_string: "Item Catalog Data {_ID.Hash} ({_ID.Hash:enum(ce.ItemDefine)}) | {_Prefab.Path}"
  app.PropCatalogUserData.PropPrefabData:
    to_string: "Prop Prefab: {_PropIDHash} | {_Prefab.Path}"
  app.GUIWeaponCatalog.GUIWeaponCatalogData:
    to_string: "GUIWeaponCatalogData {_ID.Hash:enum(ce.WeaponDefine)}"
  app.WeaponCatalogUserData.WeaponPrefabData:
    to_string: "Weapon Prefab {_WeaponID.Hash:enum(ce.WeaponDefine)}"
  app.DisplayedItemCatalog.DisplayedItemData:
    to_string: "Displayed Item {_ItemID.Hash:enum(ce.ItemDefine)} | {_Prefab.Path}"
