# TODO optimize UI for app.SuddenQuestSelectData.SelectData: display only ID + expandable event context info, or a button to open the context in a new window

entities:
  events.event:
    to_string: "Event {id}: {select_data._StartLocation:enum(app.AIKeyLocation)}"
    fields:
      - name: select_data
        label: Data
        resource:
          id: [_SerialNum]
          custom_id_range: [10000, 999000]
          type: array-file
          classname: app.SuddenQuestSelectData
          file: appsystem/quest/userdata/questsudden/suddenquesttable.user
          field: _SelectDataArray
          params:
            nested: false
  events.event_context:
    to_string: "Event context {id}: {data._Data._Type:enum(app.QuestDefine.SuddenQuestType)} - NPC={data._Data._NpcID:enum(app.CharacterID)}"
    fields:
      - name: data
        label: Data
        resource:
          id: [_SerialNum]
          custom_id_range: [10000, 999000]
          classname: app.SuddenQuestContextData
          type: array-file
          file: appsystem/quest/userdata/questsudden/suddenquesttable.user
          field: _ContextDataArray
          params:
            nested: false
  events.event_spawns:
    enums:
    - name: app.DomainQueryGenerateRequestID
      format: "CustomTable{id}"
      primary: true
    to_string: "Event spawn table {id}: {id:enum(app.DomainQueryGenerateRequestID)}"
    fields:
      - name: data
        label: Data
        resource:
          id: [_RequestID]
          classname: app.DomainQueryGenerateTable.DomainQueryGenetateTableElement
          type: array-file
          file: leveldesign/generate/domainquerygenerate/domainquerygeneratetable.user

  # app.GenerateRowData:
  #   id: [_ManualSetGuid, _AutoSetGuid] ## TODO: verify are these really unique?
  # app.GenerateTableData:
  #   id: [_TableID]
  #   group: spawns
  #   type: autoset_spawns

classes:
  app.SuddenQuestSelectData:
    to_string: "Event select data {_SerialNum}"
  app.SuddenQuestContextData:
    to_string: "Event context data {_SerialNum}"
  app.DomainQueryGenerateTable.DomainQueryGenetateTableElement:
    to_string: "Generate table {_RequestID:enum(app.DomainQueryGenerateRequestID)}"
  app.GenerateRowData:
    fields:
      _CharaID: { enum: app.CharacterID }
