entities:
  items.item_data:
    enums:
    - name: app.ItemIDEnum
      format: "It{id:06}"
      primary: true # denotes that the entity label should override this enum's corresponding display labels (entity id == enum value)
    # SmartFormat library is used for all string interpolation functionality
    # can fetch entity fields as well as nested object fields with "."
    to_string: "Item {id}: {name}"
    fields:
    - name: data
      required: true
      resource:
        id: [_Id]
        custom_id_range: [30000, 65000]
        type: merged-group
        classname: app.ItemCommonParam
        subtypes:
          app.ItemDataParam:
            type: array-file
            classname: app.ItemDataParam
            files:
            - AppSystem/Item/ItemData/ItemData.user
            - AppSystem/Item/ItemData/ExItemData.user
          app.ItemWeaponParam:
            type: array-file
            classname: app.ItemWeaponParam
            file: AppSystem/Item/ItemData/ItemWeaponData.user
          app.ItemArmorParam:
            type: array-file
            classname: app.ItemArmorParam
            file: AppSystem/Item/ItemData/ItemArmorData.user
    - name: name
      label: Name
      required: true
      field_type: keyed_message
      display_after: start
      resource:
        type: msg
        files:
        - Message/UI/ItemName.msg
        - Message/UI/ItemName_END.msg
        params:
          key_pattern: "item_name_(\\d+)"
          key_format: "item_name_{id}"
    - name: description
      label: Description
      required: true
      field_type: keyed_message
      display_after: name
      resource:
        type: msg
        files:
        - Message/UI/ItemDetail.msg
        - Message/UI/ItemDetail_END.msg
        params:
          key_pattern: "item_detail_(\\d+)"
          key_format: "item_detail_{id}"
          multiline: true
    - name: icon
      display_after: description
      # if we used vanilla tech, there would be a uvs file, added to the item master uvs file, and then an ID taken from there
      # alternatively we use content editor runtime tech, the patch needs to be saved as a CE bundle with tex and rect info
      type: DD2_ItemIcon
      field_type: DD2_ItemIcon
    - name: armorEnhanceData
      label: Enhance data
      type: app.ArmorEnhanceParam
      display_after: icon
      when:
        field: data
        property: classname
        equals: app.ItemArmorParam
      resource:
        id: [_ItemId]
        sub_id: [_Type, _EnhanceNo]
        type: array-file
        file: AppSystem/Item/ItemData/ArmorEnhanceData.user
        classname: app.ArmorEnhanceParam
    - name: weaponEnhanceData
      label: Enhance data
      display_after: icon
      when:
        field: data
        property: classname
        equals: app.ItemWeaponParam
      resource:
        id: [_ItemId]
        sub_id: [_Type, _EnhanceNo]
        type: array-file
        file: AppSystem/Item/ItemData/WeaponEnhanceData.user
        classname: app.WeaponEnhanceParam
  items.weapon:
    enums:
    - name: app.WeaponID
      format: "{name}"
      primary: true # denotes that the entity label should override this enum's corresponding display labels (entity id == enum value)
    to_string: 'Weapon {id:enum(app.WeaponID)} (#{id}): {id:reverseLookupEntity(item_data|\{data?._WeaponId@ItemWeaponParam\}|\{label\}|Unknown item)}'
    fields:
      - name: data
        label: Data
        resource:
          id: [ID]
          custom_id_range: [1000, 100000]
          type: array-file
          classname: app.WeaponCatalogData.Data
          file: AppSystem/Catalog/MainContents/Userdata/WeaponCatalogData.user
      - name: name
        type: string
        label: Weapon ID name
        required: true
        display_after: start
        resource:
          type: string
          params:
            regex: "^wp[0-9_]+$"
            regexDescription: "Example: wp00_000"
            tooltip: Enter a name for the weapon ID. This should be unique across all weapons.
            initial: "{id:enum(app.WeaponID)}"
            diffable: false
      - name: offsets
        label: Offset setting
        resource:
          id: [ID]
          type: array-file
          classname: app.WeaponSetting.OffsetSetting
          file: AppSystem/Equipment/wp/WeaponSetting.user
      # - name: prefab
      #   label: Weapon prefab
      #   required: true
      #   field_type: resource_link
      #   resource:
      #     resource_type: prefab
      #     params:
      #       path: "{data?.Prefab?.Path}"

  # app.ItemMixParam:
  #   id: [_ItemId]
  # app.ItemMixMaterialParam:
  #   id: [_ItemID]
  # app.ItemMixMaterialParam.CombineData:
  #   id: [_PairList, _CombineItem]

classes:
  app.ItemCommonParam:
    fields:
      _Id: { enum: app.ItemIDEnum, readOnly: true }
      _Attr: { enum: app.ItemAttrBits }
  app.ItemDataParam:
    to_string: "Item Data {_Id}"
    fields:
      _FakeItemId: { enum: app.ItemIDEnum }
      _DecayedItemId: { enum: app.ItemIDEnum }
      _UseAttr: { enum: app.ItemUseAttrBits }
  app.ItemWeaponParam:
    fields:
      _Job: { enum: ce.ItemJobFlags }
  app.ItemArmorParam:
    fields:
      _StyleNo: { handler: DD2.ArmorStyle }
    # - { key: HelmStyle, type: items.styles.HelmStyle, name: Style, field: _StyleNo, when: { field: _EquipCategory, equals: 2 } }
    # - { key: TopsStyle, type: items.styles.TopsStyle, name: Style, field: _StyleNo, when: { field: _EquipCategory, equals: 3 } }
    # - { key: PantsStyle, type: items.styles.PantsStyle, name: Style, field: _StyleNo, when: { field: _EquipCategory, equals: 4 } }
    # - { key: MantleStyle, type: items.styles.MantleStyle, name: Style, field: _StyleNo, when: { field: _EquipCategory, equals: 5 } }
    # - { key: FacewearStyle, type: items.styles.FacewearStyle, name: Style, field: _StyleNo, when: { field: _EquipCategory, equals: 7 } }

  app.EnhanceParamBase:
    to_string: "{_Type:enum(app.EnhanceType)} {_EnhanceNo}"
    fields:
      _Type: { enum: app.EnhanceType }
      _ItemId: { enum: app.ItemIDEnum }
      _NeedItemId0: { enum: app.ItemIDEnum }
      _NeedItemId1: { enum: app.ItemIDEnum }
  app.ItemMixParam:
    fields:
      _ItemID: { enum: app.ItemIDEnum }
      _MaterialA: { tooltip: 'Combination requires any MaterialA + any MaterialB item' }
      _MaterialB: { tooltip: 'Combination requires any MaterialA + any MaterialB item' }
      _IsNoSame: { tooltip: "Disallow picking the same item if it's present in both material sets" }
      _IsAutoMix: { tooltip: 'Possibly used for logistician?' }

  app.ItemMixMaterialParam:
    fields:
      _ItemId: { enum: app.ItemIDEnum }
  app.ItemMixMaterialParam.CombineData:
    fields:
      _PairList: { label: Items, tooltip: Combining with any item from this list will create the combine item }
      _CombineItem: { label: 'Output item' }
      _CombineMakeNum: { label: 'Output count' }
    to_string: "{_CombineItem}: {_PairList}"

  app.TopsPartsEnableItem:
    to_string: "Tops PartsEnable {_Gender:enum(app.Gender)} Job={_Job:enum(app.Character.JobEnum)} | {_TopsStyle:enum(app.TopsStyle)}"
  app.TopsAmPartsHiddenItem:
    to_string: "TopsAm PartsHidden Job={_Job:enum(app.Character.JobEnum)} | {_AmMeshID:enum(app.CharacterEditDefine.TopsAmMeshID)}"
  app.TopsBdPartsHiddenItem:
    to_string: "TopsBd PartsHidden Job={_Job:enum(app.Character.JobEnum)} | {_BdMeshID:enum(app.CharacterEditDefine.TopsBdMeshID)}"
  app.PantsLgPartsHiddenItem:
    to_string: "PantsLg PartsHidden Job={_Job:enum(app.Character.JobEnum)} | {_LgMeshID:enum(app.CharacterEditDefine.PantsLgMeshID)}"
  app.TopsBtPrimaryPartsHiddenItem:
    to_string: "BtPrimary PartsHidden Job={_Job:enum(app.Character.JobEnum)}"


# custom user-defined types (mainly useful for the content editor part, not raw file editing)
# need to have at least one field
# types:
#   _GuiRect:
#     fields:
#       x:
#         type: float
#       y:
#         type: float
#       w:
#         type: float
#       h:
#         type: float
#   DD2_ItemIcon:
#     fields:
#       icon_rect:
#         type: _GuiRect
#       icon_path:
#         type: resource
#         params:
#           resource_type: tex
#     example: # (this wouldn't be here but in the mod patch.json file and edited through UI)
#       icon_path: npc_outfits_for_arisen/npc_item_icons_01.tex.760230703
#       icon_rect: { "x": 314, "y": 314, "h": 152, "w": 152 } # TODO add tex header reading so we can determine a default rect automatically

### config field descriptions
# id: used to determine unique entities
# group: category to group the entity under
# type: simplified name of the individiual entity type; should be unique
# sub_id: for cases where an entity has one main ID but several sub-instances (e.g. item upgrade options); will get displayed as a list in the UI
# subclasses: list of subclasses of this entity type, each can have their own patcher configs
# fields: list of fields and their enum and UI overrides
# to_string: method to use to generate a quick preview string of the entity (e.g. combo list, when it's collapsed inside an array); if unspecified, concat the ID fields; if that's unspecified too, use classname
# patcher: the method of patching this object type; if unspecified, it will get patched with whatever the closest patchable parent is; if there is none, it's only used for UI purposes

# items within the same group, sharing the same ID, will get grouped into subcategories in the UI

# unresolved: how do we handle cases that have arrays of multiple different subtypes? (e.g. if there were an item array that had ArmorData and WeaponData?) are there such cases even?

### patcher types (naming TBD)
# array-file: a single user file with the root object containing an array field (takes the first array field if multiple), containing every single entity of the type
# file-catalog: a single user file that serves as a catalog of multiple array-file files
# scn-catalog: a scn file containing linked scn files per entity (quests)
# user-pfb-catalog: a user file containing a catalog of pfb files (style data, armor meshes, probably)

