entities:
  jobs.job_data:
    enums:
    - name: app.Character.JobEnum
      primary: true
    to_string: "{id:enum(app.Character.JobEnum)}"
    fields:
      - name: job_info
        label: Job Info
        type: jobs.JobInformation
        required: true
      - name: custom_skills
        label: Custom Skills
        type: jobs.CustomSkillSet
        required: true
      - name: normal_skills
        label: Normal Skills
        type: jobs.NormalSkillSet
        required: true

resources:
  jobs.JobInformation:
    id: [_JobID]
    type: array-file
    classname: app.JobInformationParam
    file: AppSystem/Gui/JobMenu/JobInformationData.user
  jobs.CustomSkillSet:
    id: [_Job]
    type: array-file
    classname: app.CustomSkillSet
    file: AppSystem/Gui/JobMenu/CustomSkillInformationData.user
  jobs.NormalSkillSet:
    id: [_Job]
    type: array-file
    classname: app.NormalSkillSet
    file: AppSystem/Gui/JobMenu/NormalSkillInformationData.user

classes:
  app.CustomSkillInformationParam:
    to_string: "{_SkillID:enum(app.HumanCustomSkillID)} : {_SkillName:translate()}"
  app.NormalSkillInformationParam:
    to_string: "{_ActionID:enum(app.NormalActionID)} ({_SkillID:enum(app.HumanNormalSkillID)}) : {_SkillName:translate()}"
