# list of resources required for a new common NPC:
# - textures - body (ALBD, NRRA), head (ALBD, NRRA)
# - spawn an NPC somewhere - natives/stm/appdata/generate/manualset/content/**/npc/normal/normal.user.2

# other, maybe useless?
# natives/stm/appdata/generate/manualset/simpleglobalnpcsettable.user.2
# natives/stm/appdata/generate/manualset/simpleglobalappendnpcsettable.user.2

# runtime hooks required (not exhaustive):
# app.CharacterIdClassification getCategoryIDFromMemberID()
# note also this might be called too early, may need to manually insert data where needed (app.NPCManager)

entities:
  characters.NpcData:
    enums:
    - name: app.CharacterID
      format: "{code}"
      primary: true
    to_string: "NPC {code}: {name}"
    before_create:
    - type: string-input
      field: code
    fields:
      - name: data
        label: Data
        required: true
        resource:
          id: [ID]
          type: object-catalog
          custom_id_range: [1000, 999999]
          filter:
          - property: _SubNPC
            equals: false
          file: AppSystem/ch/ch300/UserData/CharacterDataList.user
          classname: app.CharacterData
      - name: alternativeData
        label: Sub NPC Data
        resource:
          id: [ID]
          type: object-catalog
          custom_id_range: [1000, 999999]
          filter:
          - property: _SubNPC
            equals: true
          file: AppSystem/ch/ch300/UserData/CharacterDataList.user
          classname: app.CharacterData
      - name: edit_data
        label: Customization
        required: true
        resource:
          id: [_CharacterID]
          type: object-catalog
          classname: app.charaedit.ch000.EditDataTable.Data
          file: AppSystem/CharaEdit/ch000/EditDataTable_Npc.user
      - name: code
        label: NPC internal code name
        required: true
        display_after: start
        resource:
          type: string
          params:
            diffable: false
            regex: "^ch3[0-9_]{5}$"
            regex_description: "Example: ch302345"
            tooltip: Enter a code name for the NPC. This should be unique across all characters, used for translation keys and file names.
            initial: "{id:enum_name(app.CharacterID)}"
            unique_enum: app.CharacterID
      - name: name
        label: Name
        required: true
        display_after: code
        resource:
          type: msg
          file: Message/UI/CharacterName.msg
          params:
            key_format: "Mes_{code}"
      - name: name_sub
        label: Sub Name
        display_after: name
        resource:
          type: msg
          file: Message/UI/CharacterName.msg
          params:
            key_format: "Mes_{code}_X1"
      - name: scheduleData
        resource:
          type: item-list-catalog
          classname: app.NPCSchedule
          id: [ID]
          file: AppSystem/ch/ch300/UserData/NPCScheduleData.user

      - name: headPreBakeTexture_0
        required: true
        field_id:
          format: "{code}_0"
        resource:
          type: resource-holder-pfb
          file: AppSystem/CharaEdit/ch000/Catalog/HeadPreBakeTextureCatalog_Npc.user
          params:
            skipFields: 1
            nested: true
      - name: headPreBakeTexture_1
        field_id:
          format: "{code}_1"
        resource:
          type: resource-holder-pfb
          file: AppSystem/CharaEdit/ch000/Catalog/HeadPreBakeTextureCatalog_Npc.user
          params:
            skipFields: 1
            nested: true
      - name: headPreBakeTexture_2
        field_id:
          format: "{code}_2"
        resource:
          type: resource-holder-pfb
          file: AppSystem/CharaEdit/ch000/Catalog/HeadPreBakeTextureCatalog_Npc.user
          params:
            skipFields: 1
            nested: true
      - name: bodyPreBakeTexture_0
        required: true
        field_id:
          format: "{code}_0"
        resource:
          type: resource-holder-pfb
          file: AppSystem/CharaEdit/ch000/Catalog/BodyPreBakeTextureCatalog_Npc.user
          params:
            skipFields: 1
            nested: true
      - name: bodyPreBakeTexture_1
        field_id:
          format: "{code}_1"
        resource:
          type: resource-holder-pfb
          file: AppSystem/CharaEdit/ch000/Catalog/BodyPreBakeTextureCatalog_Npc.user
          params:
            skipFields: 1
            nested: true
      - name: bodyPreBakeTexture_2
        field_id:
          format: "{code}_2"
        resource:
          type: resource-holder-pfb
          file: AppSystem/CharaEdit/ch000/Catalog/BodyPreBakeTextureCatalog_Npc.user
          params:
            skipFields: 1
            nested: true
      - name: customLipsyncData
        resource:
          type: resource-holder-pfb
          field: _CharacterElements
          file: AppSystem/Catalog/MainContents/UserData/LipSyncCatalogUserData.user
          params:
            skipFields: 1
            nested: true

# # -> enum: app.GUITextureLoaderDefine.NPCArtTextureID, enum format "NPCArt_{code}_{variantId}_{costumeId?}"
#       - name: guiNpcTexture
#         field_id:
#           field: TODO need to match catalog entry by NPC "index" via app.GUITextureLoaderDefine.NPCArtTextureID enum
#           path:
#         resource:
#           type: resource-holder-pfb
#           file: AppSystem/Gui/UserData/NewTextureHolderData/GUINPCArtTextureHolderData.user
# # -> enum: app.GUITextureLoaderDefine.NPCThumbnailTextureID, enum format "NPCThumb_{code}_{variantId}_{costumeId?}"
#       - name: guiNpcThumbnail
#         field_id:
#           field:
#           path:
#         resource:
#           type: resource-holder-pfb
#           file: AppSystem/Gui/UserData/NewTextureHolderData/GUINPCThumbnailTextureHolderData.user
# # -> enum: app.GUITextureLoaderDefine.CorpseThumbTextureID, enum format "CorpseThumb_{code}_{variantId}"
#       - name: guiNpcCorpseThumbnail
#         field_id:
#           field:
#           path:
#         resource:
#           type: resource-holder-pfb
#           file: AppSystem/Gui/UserData/NewTextureHolderData/CorpseThumbTextureHolderData.user
classes:
  app.charaedit.ch000.EditDataTable.Data:
    to_string: "EditDataTable Character={_CharacterID:enum(app.CharacterID)}"
    fields:
      _CharacterID: { read_only: true }
  app.CharacterData:
    to_string: "{ID:enum_name(app.CharacterID)} {NameID:translate()}"
    fields:
      ID: { read_only: true }
      Present: { enum: ItemData }
      _SubSkillPresent: { enum: ItemData }
      _ItemSteal: { enum: ItemData }
      LeftWeapon: { enum: Weapon }
      RightWeapon: { enum: Weapon }
  app.facial.LipSync.Phoneme:
    to_string: "Phoneme: SoundID={_SoundMediaID}, duration={_TotalTime}"
  app.facial.LipSync.Phoneme.KeyFrame:
    to_string: "Keyframe {_Time} Vowel={_Vowel}"
  app.PartSwapTextureHolder.MaterialParam:
    to_string: "MaterialParam: {_MaterialName}.{_VariableName} = {_Texture}"
  app.DecisionPack.Decision:
    to_string: "Decision Id={_UniqueId} {_ActInterPack}"
  app.NPCSchedule:
    to_string: "NPC Schedule ID={ID:enum(app.CharacterID)} {Comments}"
  app.LipSyncCatalogUserData.PlayerElement:
    to_string: "Player Data: {_Voice:enum(app.SoundVoiceManager.PlayerVoiceType)} {_Prefab.Path}"
  app.LipSyncCatalogUserData.PawnElement:
    to_string: "Pawn Data: {_Voice:enum(app.SoundVoiceManager.PawnPersonalityType)} {_Prefab.Path}"
  app.LipSyncCatalogUserData.NPCElement:
    to_string: "Generic NPC Data: {_Voice:enum(app.CharacterData.VoiceDefine)} {_Prefab.Path}"
  app.LipSyncCatalogUserData.CharacterElement:
    to_string: "NPC Data: {_CharacterID:enum(app.CharacterID)}"
  app.charaedit.ch000.CostumeData:
    to_string: "Costume Data [ID={_CostumeID}] | {_TopsStyle:enum(app.TopsStyle)} {_PantsStyle:enum(app.PantsStyle)}"
  app.charaedit.ch000.AppearanceData:
    to_string: "Appearance Data [ID={_AppearanceID}]"
    fields:
      _HeadStyle: { enum: HeadMeshStyle }
      _SkinStyle: { enum: SkinStyle }
      _HairStyle: { enum: HairStyle }
      _BeardStyle: { enum: BeardStyle }
