# TODO natives/stm/appsystem/ai/situation/generateparameter/rootquestsituationparam.user.2
# TODO integrate quest scene resource -- natives/stm/appsystem/scene/quest.scn.20
# TODO integrate title from linked quest log resource into label

entities:
  quests.quest_data:
    fields:
    - name: context
      label: Context Data
      required: true
      resource:
        id: [_IDValue]
        type: array-file
        file: AppSystem/Quest/UserData/QuestContext.user
        field: ContextDataArray
        classname: app.QuestContextData.ContextData
    - name: variables
      label: Variable Data
      resource:
        id: [_IDValue]
        type: array-file
        file: AppSystem/Quest/UserData/QuestContext.user
        field: VariableDataArray
        classname: app.QuestContextData.VariableData
    - name: deliver
      label: Deliver Data
      resource:
        id: [_IDValue]
        type: array-file
        file: AppSystem/Quest/UserData/QuestContext.user
        field: DeliverDataArray
        classname: app.QuestContextData.DeliverData
    - name: after_story
      label: After Story Data
      resource:
        id: [_IDValue]
        type: array-file
        file: AppSystem/Quest/UserData/QuestContext.user
        field: AfterStoryDataArray
        classname: app.QuestContextData.AfterStoryData
    - name: quest_log
      label: Quest Logs
      resource:
        id: [_Id]
        type: array-file
        file: AppSystem/Catalog/MainContents/UserData/QuestLogCatalog.user
        classname: app.QuestLogCatalog.Item

classes:
  app.QuestContextData.ContextData:
    to_string: "Quest context {_IDValue}"
  app.QuestContextData.VariableData:
    to_string: "Quest variables {_IDValue}"
  app.QuestContextData.DeliverData:
    to_string: "Quest deliveries {_IDValue}"
  app.QuestContextData.AfterStoryData:
    to_string: "Quest AfterStory {_IDValue}"
  app.QuestLogCatalog.Item:
    to_string: "Quest Logs {_Id}"

  app.QuestNpcOverrideData:
    to_string: "QuestNpcOverrideData QuestId={_IDValue}"
  app.QuestNpcOverride:
    to_string: "QuestNpcOverrideData QuestId={_QuestID} NpcID={_Npc:enum(app.CharacterID)}"
  app.QuestLogResource:
    to_string: "Quest Log: {_Title:translate()}"
  app.QuestLogResource.QuestLogTaskData:
    to_string: "Task: {_BaseMsg:translate()}"
  app.QuestLogResource.QuestLogRemindData:
    to_string: "Reminder: {_BaseMsg:translate()}"
  app.QuestLogResource.QuestLogReportData:
    to_string: "Report: {_BaseMsg:translate()}"
  app.QuestLogResource.QuestLogImpossibleData:
    to_string: "Impossible: {_BaseMsg:translate()}"
  app.QuestLogConciergeData:
    to_string: "Concierge: Task {_TaskIndex}"
  app.QuestVariable:
    to_string: "Variable {_SerialNumber} ({_NameHash}): {_Variable.class_shortname}"
  app.QuestAfterStoryData.CheckVariable:
    to_string: "qu{_Condition._QuestID}.[{_Condition._NameHash}] {_Condition._CompareType:enum(app.CompareType)} {_Condition._ValueType:enum(app.QuestVariableBase.ValueTypeEnum)} {_Condition._IntValue}/{_Condition._BoolValue}"
