entities:
  shop:
    to_string: "Shop {id}: {Data._ShopNameId:translate()}"
    fields:
    - name: Data
      resource:
        file: AppSystem/Item/ItemShopData/ItemShopData.user
        type: array-file
        classname: app.ItemShopParam
        id: [_ShopId]

classes:
  app.ItemShopParam:
    to_string: "{_ShopId}: {_ShopNameId:translate()}"
    fields:
      _ShopNameId: { translate_guid: true, translate_fallback_enum: ShopNameOverrides }

  app.ItemShopSellParam:
    # id: [_ItemId]
    to_string: "{_ItemId}"
    fields:
      _ItemId: { enum: app.ItemIDEnum }

  app.ItemShopBuyParam:
    # id: [_ItemId, _Stock, _ReleaseQuestId]
    to_string: "{_ItemId} [{_Stock} stock, quest {_ReleaseQuestId}]"
    fields:
      _ItemId: { enum: app.ItemIDEnum }
