entities:
  shop:
    to_string: "Shop {id}: {data._ShopNameId:translate()}"
    fields:
    - name: data
      resource:
        file: AppSystem/Item/ItemShopData/ItemShopData.user
        type: object-catalog
        classname: app.ItemShopParam
        id: [_ShopId]
        params:
          nested: false

classes:
  app.ItemShopParam:
    to_string: "{_ShopId}: {_ShopNameId:translate()}"
    fields:
      _ShopNameId: { translate_guid: true, translate_fallback_enum: ShopNameOverrides }

  app.ItemShopSellParam:
    to_string: "{_ItemId:entity(ItemData)}"
    fields:
      _ItemId: { enum: ItemData }

  app.ItemShopBuyParam:
    to_string: "{_ItemId:entity(ItemData)} [{_Stock} stock, quest {_ReleaseQuestId}]"
    fields:
      _ItemId: { enum: ItemData }
