entities:
  items.styles.mantle.MantleStyle:
    primary_field: data
    id_field: styleNo
    to_string: "Mantle Style {id:D03}: {:findEntity(ItemData|data._StyleNo=id|data._EquipCategory=5):{label}|Unknown Item}"
    display_name: Style
    enums:
    - name: app.MantleStyle
      format: "Mantle_{id:D03}"
      value: "{styleNo.value}"
      primary: true
    fields:
    - name: DD2_StylePreview
      field_type: DD2_StylePreview
      required: true
      resource:
        params:
          dataField: _MantleStyle
          partField: _Meta._MantleStyle
    - name: data
      display_after: styleNo
      field_id: { field: styleNo, path: value }
      resource:
        type: group
        id: [_MantleStyle]
        custom_id_range: [10000, 10000000]
        classname: app.MantleSwapItem
        subtypes:
          male:
            file: AppSystem/CharaEdit/ch000/SwapData/MantleSwapData.user
            type: object-catalog
            filter:
            - property: _Gender
              equals: 2776536455
          female:
            file: AppSystem/CharaEdit/ch000/SwapData/MantleSwapData.user
            type: object-catalog
            filter:
            - property: _Gender
              equals: 1910070090
    - name: styleNo
      resource:
        type: enum_mapping
        classname: app.MantleStyle
        custom_id_range: [10000, 32700] # _MantleStyleNo on the armor data is a signed short so we need to limit to that range
        params:
          virtual_enum_name: ce.MantleStyleNo
          new_label_format: "Mantle_{id:D03}"
          label_id_parse: "Mantle_(\\d+)"
          value_from: { field: data, path: _MantleStyle }
    runtime_mapping:
      runtime_type: MantleStyle
      to_both:
        "data.female": "data.1910070090"
        "data.male": "data.2776536455"
      to_runtime:
        # null out furmask configs for runtime since it's storing pfb paths instead of direct files
        # this way it'll just read the active state which will be whichever we patched in
        "null.1": "furmasks"
        data.female._MantleStyle: styleHash
        data.male._MantleStyle: styleHash

  items.styles.mantle.MantleMesh:
    to_string: "MantleMesh {id:enum(app.CharacterEditDefine.MantleMeshID)} | {mesh._Mesh}"
    display_name: Mantle Mesh
    allow_templates: false
    enums:
    - name: "app.CharacterEditDefine.MantleMeshID"
      format: "mantle_{id}"
      primary: true
    zero_entity:
      id: 0
      label: None
    fields:
    - name: mesh
      required: true
      resource:
        custom_id_range: [10000, 10000000]
        files:
        - AppSystem/CharaEdit/ch000/Catalog/MantleMeshCatalog_Default.user
        - AppSystem/CharaEdit/ch000/Catalog/MantleMeshCatalog_40000.user
        type: resource-holder-pfb
        params:
          skipFields: 1
    - name: chain
      resource:
        files:
        - AppSystem/CharaEdit/ch000/Catalog/MantleChainCatalog_Default.user
        - AppSystem/CharaEdit/ch000/Catalog/MantleChainCatalog_40000.user
        type: resource-holder-pfb
        params:
          skipFields: 1
    - name: clsp
      resource:
        files:
        - AppSystem/CharaEdit/ch000/Catalog/MantleCollisionShapePresetCatalog_Default.user
        - AppSystem/CharaEdit/ch000/Catalog/MantleCollisionShapePresetCatalog_40000.user
        type: resource-holder-pfb
        classname: app.PartSwapCollisionShapePresetHolder
        params:
          skipFields: 1
          catalogClassname: app.PartSwapCatalog.Item
    - name: cloth
      resource:
        files:
        - AppSystem/CharaEdit/ch000/Catalog/MantleGpuClothCatalog_Default.user
        - AppSystem/CharaEdit/ch000/Catalog/MantleGpuClothCatalog_40000.user
        type: resource-holder-pfb
        params:
          skipFields: 1
    - name: sfur
      resource:
        files:
        - AppSystem/CharaEdit/ch000/Catalog/MantleShellFurCatalog_Default.user
        - AppSystem/CharaEdit/ch000/Catalog/MantleShellFurCatalog_40000.user
        type: resource-holder-pfb
        params:
          skipFields: 1
    runtime_mapping:
      runtime_type: Mantle
      to_desktop:
        Mesh: mesh
        Chain: chain
        Gpuc: cloth
        Clsp: clsp
      to_runtime:
        null.1: Mesh
        null.2: Chain
        null.3: Gpuc
        null.4: Clsp

  items.styles.mantle.MantleSkin:
    to_string: "MantleSkin {id:enum(app.CharacterEditDefine.MantleSkinID)} | {skin._Material}"
    display_name: Mantle Skin
    allow_templates: false
    enums:
    - name: app.CharacterEditDefine.MantleSkinID
      format: "mantle_{id}"
      primary: true
    zero_entity:
      id: 0
      label: None
    fields:
    - name: skin
      required: true
      resource:
        files:
        - AppSystem/CharaEdit/ch000/Catalog/MantleSkinCatalog_Default.user
        - AppSystem/CharaEdit/ch000/Catalog/MantleSkinCatalog_40000.user
        custom_id_range: [10000, 10000000]
        type: resource-holder-pfb
        params:
          skipFields: 1
    runtime_mapping:
      runtime_type: MantleSkin
      to_desktop:
        Skin: skin
      to_runtime:
        null.s: Skin

classes:
  app.MantleSwapItem:
    to_string: "{class_shortname} {_MantleStyle:enum(app.MantleStyle)} {_Gender:enum(app.Gender)}"
    fields:
      _MantleStyle: { read_only: true }
      _Gender: { read_only: true }
      _MeshID: { enum: MantleMesh, label: Mesh }
      _SkinID: { enum: MantleSkin, label: Skin }
      _PartsEnable: { default: 15363 }
