entities:
  charaEdit.hair.HairStyle:
    primary_field: data
    to_string: "Hair {data._HairStyle:enum(app.HairStyle)} [#{id}]"
    display_name: Style
    enums:
    - name: app.HairStyle
      format: "Style_{id:D03}"
      primary: true
    fields:
    - name: DD2_StylePreview
      field_type: DD2_StylePreview
      required: true
      resource:
        params:
          dataField: _HairStyle
          partField: _Meta._HairStyle
    - name: data
      required: true
      resource:
        id: [_HairStyle]
        custom_id_range: [10000, 10000000]
        classname: app.HairSwapItem
        file: AppSystem/CharaEdit/ch000/SwapData/HairSwapData.user
        type: object-catalog
        params:
          nested: false

  charaEdit.hair.HairMesh:
    to_string: "HairMesh {id:enum(app.CharacterEditDefine.HairMeshID)} | {mesh._Mesh}"
    display_name: Hair Mesh
    enums:
    - name: "app.CharacterEditDefine.HairMeshID"
      format: "Hair_{id}"
      primary: true
    zero_entity:
      id: 0
      label: None
    fields:
    - name: mesh
      required: true
      resource:
        custom_id_range: [10000, 10000000]
        files:
        - AppSystem/CharaEdit/ch000/Catalog/HairMeshCatalog_Default.user
        - AppSystem/CharaEdit/ch000/Catalog/HairMeshCatalog_40000.user
        type: resource-holder-pfb
        params:
          skipFields: 1
    - name: chain
      resource:
        files:
        - AppSystem/CharaEdit/ch000/Catalog/HairChainCatalog_Default.user
        - AppSystem/CharaEdit/ch000/Catalog/HairChainCatalog_40000.user
        type: resource-holder-pfb
        params:
          skipFields: 1
    - name: clsp
      resource:
        files:
        - AppSystem/CharaEdit/ch000/Catalog/HairClspCatalog_Default.user
        - AppSystem/CharaEdit/ch000/Catalog/HairClspCatalog_40000.user
        type: resource-holder-pfb
        classname: app.PartSwapCollisionShapePresetHolder
        params:
          skipFields: 1

  charaEdit.hair.HairSkin:
    to_string: "HairSkin {id:enum(app.CharacterEditDefine.HairSkinID)} | {skin._Material}"
    display_name: Hair Skin
    enums:
    - name: app.CharacterEditDefine.HairSkinID
      format: "Hair_{id}"
      primary: true
    zero_entity:
      id: 0
      label: None
    fields:
    - name: skin
      required: true
      resource:
        files:
        - AppSystem/CharaEdit/ch000/Catalog/HairSkinCatalog_Default.user
        - AppSystem/CharaEdit/ch000/Catalog/HairSkinCatalog_40000.user
        custom_id_range: [10000, 10000000]
        type: resource-holder-pfb
        params:
          skipFields: 1
    - name: skinBeast
      required: true
      resource:
        files:
        - AppSystem/CharaEdit/ch000/Catalog/HairSkinCatalog_Default_BA.user
        - AppSystem/CharaEdit/ch000/Catalog/HairSkinCatalog_40000_BA.user
        type: resource-holder-pfb
        params:
          skipFields: 1

classes:
  app.HairSwapItem:
    to_string: "{class_shortname} {_HairStyle:enum(app.HairStyle)}"
    fields:
      _HairStyle: { read_only: true }
      _MeshID: { enum: HairMesh, label: Mesh }
      _SkinID: { enum: HairSkin, label: Skin }
