classes:
  app.TalkEventResourcePack.PackData:
    to_string: "TalkEvent Pack TalkEventId={_Data._Id}"
  app.TalkEventDefine.TalkEventData:
    # id: [_Id]
    to_string: "TalkEvent Data Id={_Id}"
  app.NpcCommonTalkData:
    to_string: "CommonTalkData Voice={_VoiceVariation}"
  app.NpcUniqueTalkData:
    to_string: "UniqueTalkData CharaID={_CharaID}"
  app.NpcSituationTalkData:
    to_string: "NpcSituationTalkData [{_ID}] {_Name}"
  app.NpcCommonTalkSituation:
    to_string: "CommonTalkSituation [{_ID}] {_Name}"
  app.NpcJobTypeTalkSituations:
    to_string: "JobTypeTalkSituations {_JobType}"
  app.Ch230TalkData:
    to_string: "Ch230TalkData Voice={_Voice}"
  app.NpcTalkForbiddenData:
    to_string: "NpcTalkForbiddenData {_CharaID}"
  app.TalkEventDialogueUserData.DefaultSegment:
    to_string: "Talk Segment {_SegmentName}"
    auto_expand: false
  app.TalkEventDialogueUserData.ChoiceSegment:
    to_string: "Choice Segment {_SegmentName}"
    auto_expand: false
  app.TalkEventDialogueUserData.Dialogue:
    to_string: "Dialogue [{_SpeakerId:enum(app.CharacterID)}]: {_MsgId:translate()}"
  app.TalkEventDialogueCatalog.DialoguePack:
    to_string: "DialoguePack {_QuestId:enum(app.QuestDefine.ID)}"
