# additional data:
# - weather schedules: AppSystem/Weather/Weatherschedulesetting1.user  (and additional 2-6 files)
# - grid -> weather mapping: editdata/gridattribute/weather/gridattributeweather.user

entities:
  weather:
    to_string: "Weather {id}: {data.Area:enum(app.WeatherArea)} {data.Weather:enum(app.WeatherManager.WeatherEnum)}"
    fields:
    - name: data
      label: Data
      required: true
      resource:
        id: [Area, Weather]
        type: array-file
        file: AppSystem/Weather/WeatherUserData.user
        classname: app.WeatherUserData.WeatherData
        params:
          nested: false
    - name: postEffects
      label: Post Effects
      required: true
      display_after: start
      resource:
        id: [Area, Weather]
        sub_id: [StartHour, EndHour]
        type: array-file
        file: AppSystem/Weather/WeatherPostEffectUserData.user
        classname: app.WeatherManager.WeatherPostEffect.PostEffectData

classes:
  app.WeatherUserData.WeatherData:
    to_string: "Weather Data {Area:enum(app.WeatherArea)} {Weather:enum(app.WeatherManager.WeatherEnum)}"
  app.WeatherManager.WeatherPostEffect.PostEffectData:
    to_string: "Weather Effects {Area:enum(app.WeatherArea)} {Weather:enum(app.WeatherManager.WeatherEnum)} [{StartHour}~{EndHour}]"
