# grid -> weather mapping: editdata/gridattribute/weather/gridattributeweather.user
# main weather data: AppSystem/Weather/WeatherUserData.user

# additional data:
# - post effect settings: AppSystem/Weather/Weatherposteffectuserdata.user
# - weather schedules: AppSystem/Weather/Weatherschedulesetting1.user  (and additional 2-6 files)

entities:
  weather:
    to_string: "Weather {id}: {data.Area:enum(app.WeatherArea)} {data.Weather:enum(app.WeatherManager.WeatherEnum)}"
    fields:
    - name: data
      label: Data
      required: true
      resource:
        id: [Area, Weather]
        type: array-file
        file: AppSystem/Weather/WeatherUserData.user
        classname: app.WeatherUserData.WeatherData
        params:
          nested: false

classes:
  app.WeatherUserData.WeatherData:
    to_string: "Weather Data {Area:enum(app.WeatherArea)} {Weather:enum(app.WeatherManager.WeatherEnum)}"
