# character/it/prefab_resourceitem/ri3115/ri3115_inventory.pfb

entities:
  weapon:
    enums:
    - name: offline.EquipmentDefine.WeaponType
      format: "{name}"
      primary: true
    to_string: "Weapon {id}: {data.Basic.NameMessageID:translate()}"
    fields:
      - name: data
        type: app.ItemSpecificationData.SpecUnit
        label: Data
        required: true
        resource:
          params:
            nested: false
      # prefab:
      #   label: Weapon prefab
      #   required: true
      #   params:
      #     type: resource_link
      #     resource_type: prefab
      #     path: "{catalog?.Prefab?.Path}"

resources:
  app.ItemSpecificationData.SpecUnit:
    id: [ItemID]
    type: array-file
    file: natives/stm/singletonuserdatas/playerweaponspecificationdata.user.2

classes:
  app.ItemSpecificationData.SpecUnit:
    to_string: "Item {ItemID}: {Basic.NameMessageID:translate()}"
