# character/it/prefab_resourceitem/ri3115/ri3115_inventory.pfb

entities:
  Item:
    enums:
    - name: offline.EquipmentDefine.WeaponType
      primary: true
    to_string: "Item {data.ItemID} {id}: {weaponSpec?.Basic?.NameMessageID:translate()}"
    fields:
    - name: data
      required: true
      resource:
        type: object-catalog
        id: [ItemIDHash]
        classname: app.InventoryItemPrefabHolder.Unit
        custom_id_range: [1000, 999999]
        file: SingletonUserDatas/inventoryitemprefabholderother.user
        params:
          duplicate_assets_on_create: true
    - name: weaponSpec
      label: Weapon Spec
      resource:
        id: [ItemID]
        type: object-catalog
        classname: app.ItemSpecificationData.SpecUnit
        file: SingletonUserDatas/PlayerWeaponSpecificationData.user
        params:
          nested: false

classes:
  app.ItemSpecificationData.SpecUnit:
    to_string: "Item {ItemID}: {Basic.NameMessageID:translate()}"
  app.InventoryItemPrefabHolder.Unit:
    to_string: "ItemPrefabHolder {ItemID} [{ItemIDHash}]"
