# natives/stm/appsystem/event/timelineevent/actorplayerweapondisplayuserdata.user.3

entities:
  costumes.costume_catalog_unit:
    custom_id_range: [100000, 999999]
    to_string: "Costume [{data[0]?._CostumeId}]"
    fields:
      data:
        type: objectArray
        label: Data
        required: true
        param:
          classname: app.TimelineEventCostumeCatalog.Unit
  # costumes.montage_preset:
  #   custom_id_range: [100000, 999999]
  #   to_string: "Montage Preset [{data._Preset._ModelID} / {data._Preset._ID}]"
  #   fields:
  #     data:
  #       type: objectArray
  #       label: Data
  #       required: true
  #       param:
  #         classname: app.CharacterMontagePresetCatalogUserData.Entry

classes:
  app.TimelineEventCostumeCatalog.Unit:
    id: [_CostumeId]
    subId: [_CostumeVariationId]
    to_string: "Costume {_CostumeId} (Variation: {_CostumeVariationId})"
    patcher:
      type: array-file
      file: natives/stm/event/resource/costumecatalog/ch0200.user.3
      # file: natives/stm/event/resource/costumecatalog/ch1300.user.3
  app.MontageData.MontageParts:
    to_string: "{_PartsName}: {_PrefabResource?.Path}"
  app.BounsMontageData:
    to_string: "Bonus Montage {_BonusID} - Model {_ModelID} / Preset {_DefaultPresetID}"
  app.BounsMontageData.ScenarioData:
    to_string: "ScenarioData {_Type} _PresetID={_PresetID}"
  app.NameHash:
    to_string: "NameHash: {_Hash}"
  app.FigureItemCatalog.Data:
    to_string: "FigureItemCatalogData {_BonusID} Category={_ItemCategoryID}"
  app.CharacterMontagePresetCatalogUserData.Entry:
    # TODO nested IDs not supported yet
    # id: [_Preset._ModelID]
    # subId: [_Preset._ID]
    to_string: "Montage Preset Entry [{_Preset._ModelID} / {_Preset._ID}] {:path(_Preset)}"
    # patcher:
    #   type: array-file
    #   file: natives/stm/gameassets/character/characterprefab/cp_e9/cp_e900/montage/cp_e900charactermontagepresetcataloguserdata.user.3
    #   file: natives/stm/gameassets/character/characterprefab/cp_a1/cp_a100/userdata/cp_a100montagepresetdata.user.3
    #   file: natives/stm/appsystem/event/timelineevent/catalog/timelineevent_charactermontagepresetcataloguserdata.user.3
    #   file: natives/stm/appsystem/event/timelineevent/catalog/timelineevent_charactermontagepresetcataloguserdata_1stchunk.user.3
