entities:
  items.item_data:
    to_string: "Item [{data._ItemIDStr}]: {name}"
    fields:
    # TODO: add an easy UI link to the prefab of ItemData
    - name: data
      required: true
      display_after: caption
      resource:
        id: [_ItemIDStr]
        type: array-file
        custom_id_range: [100000, 999999]
        classname: app.ItemCatalogUserData.ItemData
        file: leveldesign/item/userdata/itemcataloguserdata.user
    - name: name
      label: Name
      required: true
      resource:
        type: msg
        file: message/gamesystem/item.msg
        params:
          key_format: "Item_Name_{data._ItemIDStr}"
    - name: caption
      label: Caption
      required: true
      resource:
        type: msg
        file: message/gamesystem/item.msg
        params:
          key_format: "Item_Caption_{data._ItemIDStr}"
          multiline: true
    - name: gui_data
      label: GUI Data
      resource:
        id: [_ItemIdStr]
        type: array-file
        classname: app.GuiItemInfo
        file: gui/userdata/guiitemdata.user
    - name: detail_search
      label: Details Prefab
      required: true
      resource:
        id: [_IDStr]
        type: array-file
        classname: app.DetailSearchCatalogUserData`1.ObjectData<app.ItemID>
        file: gameassets/item/userdata/detailsearchitemcatalog.user
    - name: craft_sound
      label: Craft Sound
      required: true
      resource:
        id: [_ItemID]
        type: array-file
        classname: app.CraftRecipeCatalogUserData.CraftSoundCatalogUserData.CatalogData
        file: sound/craftsoundcataloguserdata.user
  items.craft_recipe:
    to_string: Recipe [{data._RecipeIDStr}] => {data._ProductItems.0._ItemID:translate_fmt(Item_Name_$0)}
    fields:
    - name: data
      label: Data
      required: true
      resource:
        id: [_RecipeIDStr]
        type: array-file
        classname: app.CraftRecipe
        file: leveldesign/item/userdata/craftrecipecataloguserdata.user

classes:
  app.ItemCatalogUserData.ItemData:
    to_string: "ItemData {_ItemIDStr}"
  app.GuiItemInfo:
    to_string: "GuiItemInfo {_ItemIdStr}"
  app.DetailSearchCatalogUserData`1.ObjectData<app.ItemID>:
    to_string: "DetailSearchCatalog {_IDStr}"
  app.CraftRecipeCatalogUserData.CraftSoundCatalogUserData.CatalogData:
    to_string: "Craft Sound {_ItemID}"
  app.CraftRecipe:
    to_string: Crafting Recipe {_RecipeIDStr}
  app.CraftRecipe.MaterialItemData_Basic:
    to_string: "Crafting Material: {_Stock}x {_ItemID} ({_ItemID:translate_fmt(Item_Name_$0)})"
  app.CraftRecipe.MaterialItemData_Contained:
    to_string: "Crafting Material: {_Stock}x {_ItemID} ({_ItemID:translate_fmt(Item_Name_$0)}) [discounts]"
  app.CraftRecipe.ProductItemData_Basic:
    to_string: "Crafting Product: {_Stock}x {_ItemID} ({_ItemID:translate_fmt(Item_Name_$0)})"
  app.CraftRecipe.OptionalData:
    to_string: "Discount {_EffectiveItemID}: {_Value}"

  app.ItemCarryOverSettingUserData.CarryOverItemSetting:
    to_string: "Item Carry Over Settings {_ItemID}"
    # leveldesign/item/userdata/itemcarryoversetting.user

# TODO prices (3 separate files per difficulty) leveldesign/shop/userdata/shopitempriceuserdata.user