# TODO
# weapon specific hold settings: appsystem/character/characterprefab/playercommon/userdata/playerweaponhold.user
# weapon category settings: gameassets/character/additionaldata/weaponcategoryfordamageconfiguration/weaponcategoryfordamageconfiguration.user

entities:
  weapons.weapon:
    # lord forgive me
    to_string: "Weapon [{data._WeaponID}]: {data._WeaponParameter?._WeaponResourceParam?.ResourceData?[0]?._WeaponItemIDStrArray?[0]:translate_fmt(Item_Name_$0)}"
    fields:
    - name: data
      required: true
      resource:
        classname: app.WeaponParamCatalogUserData.Data
        id: [_WeaponID]
        type: array-file
        custom_id_range: [100000, 999999]
        files:
        - gameassets/weapon/catalog/weaponparamcataloguserdata.user
        - gameassets/weapon/catalog/weaponparamcataloguserdata_firstchunk.user
    - name: mesh_catalog
      label: Mesh Catalog
      required: true
      resource:
        id: [_WeaponID]
        classname: app.WeaponCatalogUserData.Data
        type: array-file
        files:
        - gameassets/weapon/catalog/weaponcataloguserdata.user
        - gameassets/weapon/catalog/weaponcataloguserdata_firstchunk.user
  weapons.accessory:
    to_string: "Accessory [{data._ID}]"
    fields:
    - name: data
      required: true
      resource:
        id: [_ID]
        type: array-file
        classname: app.WeaponAccessoryCatalogUserData.Data
        files:
        - gameassets/weapon/catalog/weaponaccessorycataloguserdata.user
        - gameassets/weapon/catalog/weaponaccessorycataloguserdata_firstchunk.user

resources:
  weapons.sling_preset:
    id: [_WeaponID]
    type: array-file
    classname: app.PlayerSlingWeaponChainPresetConfiguration.PlayerSlingWeaponChainPresetUserData.SlingWeaponChainPresetData
    file: appsystem/character/characterprefab/playercommon/userdata/playerslingweaponchainpresetuserdata.user
  weapons.attachment_catalog:
    id: [_AttachmentID]
    type: array-file
    classname: app.WeaponAttachmentCatalogUserData.Data
    files:
    - gameassets/weapon/catalog/weaponattachmentcatalog.user
    - gameassets/content/dlc/dlc_02/weaponattachmentcatalog_dlc_02.user
  weapons.attachment_param_catalog:
    id: [_AttachmentID]
    type: array-file
    classname: app.WeaponAttachmentParamCatalogUserData.Data
    files:
    - gameassets/weapon/catalog/weaponattachmentparamcataloguserdata.user
    - gameassets/content/dlc/dlc_02/weaponattachmentparamcataloguserdata_dlc_02.user

  # app.WeaponAccessoryParamBase.Data:
  #   id: [_ID]

classes:
  app.WeaponCatalogUserData.Data:
    to_string: "Weapon {_WeaponID}"
  app.WeaponParamCatalogUserData.Data:
    to_string: "Weapon Param {_WeaponID}"
  app.PlayerSlingWeaponChainPresetConfiguration.PlayerSlingWeaponChainPresetUserData.SlingWeaponChainPresetData:
    to_string: "Sling Weapon Chain Preset {_WeaponID}"
  app.WeaponAttachmentCatalogUserData.Data:
    to_string: "Weapon Attachment Param {_AttachmentID}"
  app.WeaponAttachmentParamCatalogUserData.Data:
    to_string: "Weapon Attachment Param {_AttachmentID}"

  app.WeaponAccessoryParamBase.Data:
    to_string: "Accessory Param {_ID}"
  app.WeaponAccessoryCatalogUserData.Data:
    to_string: "AccessoryCatalog {_ID}"
