name: Build the app

on: push

jobs:
  release:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v6
      with:
        submodules: recursive
        fetch-depth: 0
        persist-credentials: false
        lfs: true

    - name: Restore dependencies (Windows)
      run: dotnet restore -r win-x64

    - name: Set outputs
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $env:GITHUB_OUTPUT

    - name: Publish debug build (Windows)
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      run: |
        dotnet publish -c Debug --no-restore -f net10.0-windows /p:Platform=x64 /p:RuntimeIdentifier=win-x64 /p:VersionSuffix=r${{ steps.vars.outputs.sha_short }} -o build/win64 ContentEditor.App/ContentEditor.App.csproj

    - name: Publish release app (Windows)
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        $TAG="${{ github.ref_name }}".Replace("v","")
        dotnet publish -c Release --no-restore -f net10.0-windows /p:Platform=x64 /p:RuntimeIdentifier=win-x64 /p:DebugType=none /p:DebugSymbols=false /p:VersionPrefix=$TAG -o build/win64 ContentEditor.App/ContentEditor.App.csproj

    - name: Restore dependencies (Linux)
      run: dotnet restore -r linux-x64

    - name: Publish debug build (Linux)
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      run: |
        dotnet publish -c Debug --no-restore -f net10.0 /p:Platform=x64 /p:RuntimeIdentifier=linux-x64 /p:VersionSuffix=r${{ steps.vars.outputs.sha_short }} -o build/linux ContentEditor.App/ContentEditor.App.csproj

    - name: Publish release app (Linux)
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        $TAG="${{ github.ref_name }}".Replace("v","")
        dotnet publish -c Release --no-restore -f net10.0 /p:Platform=x64 /p:RuntimeIdentifier=linux-x64 /p:DebugType=none /p:DebugSymbols=false /p:VersionPrefix=$TAG -o build/linux ContentEditor.App/ContentEditor.App.csproj

    - name: ZIP files for release
      run: |
        cd build/win64/
        7z a ContentEditor-win64.zip *
        cd ../linux/
        7z a ContentEditor-linux.zip *

    - name: Upload artifacts (Windows)
      uses: actions/upload-artifact@v7
      with:
        name: ContentEditor-win64
        path: build/win64/ContentEditor-win64.zip
        include-hidden-files: true
        archive: false

    - name: Upload artifacts (Linux)
      uses: actions/upload-artifact@v7
      with:
        name: ContentEditor-linux
        path: build/linux/ContentEditor-linux.zip
        include-hidden-files: true
        archive: false

    - name: Upload files to release
      uses: softprops/action-gh-release@v3
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          build/win64/*.zip
          build/linux/*.zip
